### ISSUE TITLE
Use Buf plugin

### ISSUE THREAD

**Issue by kevinmichaelchen** [openmarketplaceengine/ome-proto-ts#2]
https://github.com/stephenh/ts-proto/pull/573

We can use Buf to remotely compile code to TS, so we can remove the dependency on https://github.com/ory/build-buf-action

**Comment by kevinmichaelchen** [comment]
`./buf.gen.yaml`
```yaml
version: v1
plugins:
  - remote: buf.build/stephenh/plugins/ts-proto
    out: gen/ts
    opt:
      - esModuleInterop=true
      - outputServices=nice-grpc
      - outputServices=generic-definitions
      - useExactTypes=false
```

Running
```
buf generate openmarketplaceengine --template buf.gen.yaml
```

Yields file structure:
```
$ tree gen

gen
└── ts
   ├── api
   │  ├── crossing
   │  │  └── v1beta1
   │  │     └── crossing.ts
   │  ├── job
   │  │  └── v1beta1
   │  │     └── job.ts
   │  ├── location
   │  │  └── v1beta1
   │  │     ├── detect.ts
   │  │     ├── location.ts
   │  │     └── location_update.ts
   │  ├── status
   │  │  └── v1beta1
   │  │     └── uptime.ts
   │  ├── tollgate
   │  │  └── v1beta1
   │  │     └── tollgate.ts
   │  ├── type
   │  │  └── v1beta1
   │  │     ├── crossing.ts
   │  │     ├── location.ts
   │  │     └── movement.ts
   │  └── worker
   │     └── v1beta1
   │        └── worker.ts
   └── google
      └── protobuf
         ├── empty.ts
         └── timestamp.ts
```
